project:
  name: "airportmap"
  version: "2.0.0"

paths:
  source: "./src"
  output: "./dist"
  temp: "./temp"
  buildScripts: "./build-scripts"

build:
  typescript:
    server:
      configFile: "./tsconfig.server.json"
    client:
      configFile: "./tsconfig.client.json"
