i18n:
  repository: "https://github.com/airportmap/i18n.git"
  branch: "master"
  target: "locales"
  pattern: "{{lng}}/{{ns}}.json"

  languages:
    - "en"
    - "de"

  namespaces:
    - "app.generic"

  fallback:
    language: "en"
    namespace: "app.generic"
