server:
  host: "airportmap.de"
  https: true
  port: 3000
  debug: false

i18n:
  defaultLanguage: "en-US"
  supportedLanguages: [ "en-US", "de-DE" ]
  namespaces: [
    "app.generic"
  ]

modules:
  enabled: []

paths:
  views: "./src/shared/views"
  public: "./dist/public"
  locales: "./src/locales"
